
/**************************************************************
 *	
 *	BgMusic, 8 bit, 8000Hz,
 *	1 channel, 612853 bytes/channel
 *	Total Size: 1 * 612853 + 4 (header) = 613023 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\brandon\Desktop\BgMusic.wav
 *	Time-stamp: Tue Nov 04 18:30:46 2014
 *	
 **************************************************************/

#ifndef __BGMUSICH__
#define __BGMUSICH__

#define BGMUSICFREQ 8000
#define BGMUSICLEN 612853

extern const unsigned char BgMusic[612853];

#endif /* __BGMUSICH__ */
