
/**************************************************************
 *	
 *	CaitlynShot, 8 bit, 44100Hz,
 *	1 channel, 76224 bytes/channel
 *	Total Size: 1 * 76224 + 4 (header) = 76268 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\brandon\Desktop\CaitlynShot.wav
 *	Time-stamp: Wed Nov 19 00:25:54 2014
 *	
 **************************************************************/

#ifndef __CAITLYNSHOTH__
#define __CAITLYNSHOTH__

#define CAITLYNSHOTFREQ 44100
#define CAITLYNSHOTLEN 76224

extern const unsigned char CaitlynShot[76224];

#endif /* __CAITLYNSHOTH__ */
