
/**************************************************************
 *	
 *	CharSelect, 8 bit, 8000Hz,
 *	1 channel, 536879 bytes/channel
 *	Total Size: 1 * 536879 + 4 (header) = 537119 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\brandon\Desktop\CharSelect.wav
 *	Time-stamp: Tue Nov 04 18:30:44 2014
 *	
 **************************************************************/

#ifndef __CHARSELECTH__
#define __CHARSELECTH__

#define CHARSELECTFREQ 8000
#define CHARSELECTLEN 536879

extern const unsigned char CharSelect[536879];

#endif /* __CHARSELECTH__ */
