
/**************************************************************
 *	
 *	Defeat, 8 bit, 44100Hz,
 *	1 channel, 131402 bytes/channel
 *	Total Size: 1 * 131402 + 4 (header) = 131446 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\brandon\Desktop\Defeat.wav
 *	Time-stamp: Wed Nov 19 00:26:03 2014
 *	
 **************************************************************/

#ifndef __DEFEATH__
#define __DEFEATH__

#define DEFEATFREQ 44100
#define DEFEATLEN 131402

extern const unsigned char Defeat[131402];

#endif /* __DEFEATH__ */
