
/**************************************************************
 *	
 *	GunShot, 8 bit, 22050Hz,
 *	1 channel, 11121 bytes/channel
 *	Total Size: 1 * 11121 + 4 (header) = 11165 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\brandon\Desktop\GunShot.wav
 *	Time-stamp: Thu Nov 27 22:32:06 2014
 *	
 **************************************************************/

#ifndef __GUNSHOTH__
#define __GUNSHOTH__

#define GUNSHOTFREQ 22050
#define GUNSHOTLEN 11121

extern const unsigned char GunShot[11121];

#endif /* __GUNSHOTH__ */
