
/**************************************************************
 *	
 *	TeemoDeath, 8 bit, 48000Hz,
 *	1 channel, 62208 bytes/channel
 *	Total Size: 1 * 62208 + 4 (header) = 62336 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\brandon\Desktop\TeemoDeath.wav
 *	Time-stamp: Thu Nov 27 23:06:30 2014
 *	
 **************************************************************/

#ifndef __TEEMODEATHH__
#define __TEEMODEATHH__

#define TEEMODEATHFREQ 48000
#define TEEMODEATHLEN 62208

extern const unsigned char TeemoDeath[62208];

#endif /* __TEEMODEATHH__ */
