
/**************************************************************
 *	
 *	TeemoMove, 8 bit, 44100Hz,
 *	1 channel, 97844 bytes/channel
 *	Total Size: 1 * 97844 + 4 (header) = 98084 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\brandon\Desktop\TeemoMove.wav
 *	Time-stamp: Thu Nov 27 12:54:42 2014
 *	
 **************************************************************/

#ifndef __TEEMOMOVEH__
#define __TEEMOMOVEH__

#define TEEMOMOVEFREQ 44100
#define TEEMOMOVELEN 97844

extern const unsigned char TeemoMove[97844];

#endif /* __TEEMOMOVEH__ */
