
/**************************************************************
 *	
 *	TeemoShot, 8 bit, 44100Hz,
 *	1 channel, 18638 bytes/channel
 *	Total Size: 1 * 18638 + 4 (header) = 18878 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\brandon\Desktop\TeemoShot.wav
 *	Time-stamp: Wed Nov 19 00:25:58 2014
 *	
 **************************************************************/

#ifndef __TEEMOSHOTH__
#define __TEEMOSHOTH__

#define TEEMOSHOTFREQ 44100
#define TEEMOSHOTLEN 18638

extern const unsigned char TeemoShot[18638];

#endif /* __TEEMOSHOTH__ */
