
/**************************************************************
 *	
 *	Victory, 8 bit, 44100Hz,
 *	1 channel, 127420 bytes/channel
 *	Total Size: 1 * 127420 + 4 (header) = 127660 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\brandon\Desktop\Victory.wav
 *	Time-stamp: Wed Nov 19 00:26:00 2014
 *	
 **************************************************************/

#ifndef __VICTORYH__
#define __VICTORYH__

#define VICTORYFREQ 44100
#define VICTORYLEN 127420

extern const unsigned char Victory[127420];

#endif /* __VICTORYH__ */
